### ISSUE TITLE
No drop down menu

### ISSUE THREAD

**Issue by WxlfB3t7er** [DxltaMath/DMIx#14]
there was no drop down menu just a pop up that said "DxltaMath
[This is free and open-source software](https://github.com/DxltaMath/license/blob/master/dGUI-License.txt). If you paid for this or accessed this behind a paywall/AdFly link, demand a refund. If you sell this software, or otherwise make a commercial advantage from it, you are violating [our license](https://github.com/DxltaMath/license/blob/master/dGUI-License.txt)." so I hit accept and It did not do anything is there any way to fix it I tried the manual install and the extension install but nether seemed to work...

**Comment by WxlfB3t7er** [comment]
I fixed it

**Comment by JackWagon885** [comment]
"I fixed it"

**Comment by afkvido** [comment]
It's working?

**Comment by afkvido** [comment]
@wqlfgxmes

**Comment by JackWagon885** [comment]
It's not working, that's why I commented "I fixed it", though I should've looked at the dates.
