### ISSUE TITLE
School chromebook.

### ISSUE THREAD

**Issue by YaBoyMH** [DxltaMath/DMIx#2]
When i'm on a school chromebook and I cant get extensions how can I get just the javascript: for my book mark.

**Comment by afkvido** [comment]
Not really a thing right now.

**Comment by JackWagon885** [comment]
You can use Skiovox, as you can download extensions while in Skiovox.

**Comment by afkvido** [comment]
@JackWagon885 It's a great thing however DMIx is unsupported at the moment
