### ISSUE TITLE
Main.js

### ISSUE THREAD

**Issue by JackWagon885** [DxltaMath/DMIx#22]
Whenever I reload Deltamath, it gives me an error message saying "failed to fetch main.js", which after checking, no longer exists.

**Comment by afkvido** [comment]
Sorry, the extension isn't working at the moment. This project's mostly dead, I'm too busy to fix it

**Comment by JackWagon885** [comment]
You should make time for it, this is basically the only Deltamath hack out there & a lot of people want it back, though of course it's possible you can't or you just don't want to.

**Comment by afkvido** [comment]
Ill do it if you can find me a few more devs to work on this

**Comment by JackWagon885** [comment]
I'd work on it if I knew how to code

**Comment by afkvido** [comment]
Learn

**Comment by JackWagon885** [comment]
ok let me just "get money"

**Comment by afkvido** [comment]
Many free JS courses online @JackWagon885
